import { build } from 'esbuild';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const result = await build({
  absWorkingDir: root,
  entryPoints: ['src/core.mjs'], outfile: 'js/core.js',
  bundle: true, format: 'iife', globalName: 'DevKitCore',
  platform: 'browser', target: 'es2020', minify: true,
  legalComments: 'none', metafile: true, write: false,
  banner: { js: '// Generated by npm run build:core. Licenses: vendor-licenses.txt' },
});

const packages = new Map();
for (const input of Object.keys(result.metafile.inputs).filter(name => name.includes('node_modules/'))) {
  let dir = path.dirname(path.join(root, input));
  while (dir !== root) {
    try {
      const pkg = JSON.parse(await readFile(path.join(dir, 'package.json'), 'utf8'));
      if (pkg.name && pkg.version) { packages.set(dir, pkg); break; }
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
    dir = path.dirname(dir);
  }
}
const licenses = [];
for (const [dir, pkg] of [...packages].sort((a, b) => a[1].name.localeCompare(b[1].name))) {
  const files = (await readdir(dir)).filter(name => /^(licen[cs]e|copying)(\.|$)/i.test(name)).sort();
  if (!files.length) throw new Error(`Missing license for ${pkg.name}`);
  licenses.push(`${pkg.name}@${pkg.version} (${pkg.license})\n\n` +
    (await Promise.all(files.map(file => readFile(path.join(dir, file), 'utf8')))).join('\n'));
}
const outputs = [
  ...result.outputFiles.map(file => [file.path, file.text]),
  [path.join(root, 'js/vendor-licenses.txt'), licenses.join('\n\n---\n\n') + '\n'],
];
for (const [file, text] of outputs) {
  if (process.argv.includes('--check')) {
    if (await readFile(file, 'utf8') !== text) throw new Error(`Run npm run build:core to update ${path.relative(root, file)}`);
  } else {
    await writeFile(file, text);
  }
}
